### ISSUE TITLE
Nelze zadat větší číslo než 10 do násobitele

### ISSUE THREAD

**Issue by vaclavaki** [stenlyk/nasobilka#1]
V případě příkladu, kdy je znám výsledek a my máme doplnit násobitele, nelze zadat větší číslo jak 10.
Konkrétní příklad:
2 * X = 34

Při zadání X se zobrazí:
Hodnota musí být menší nebo rovna 10 

![chyba_nasobeni](https://user-images.githubusercontent.com/64246772/80181479-3f1c5000-8605-11ea-8b20-c4e04fe7cd6a.png)

**Comment by stenlyk** [comment]
Díky právě jsem nasadil novou verzi 0.4.1 kde je to opravené
